config/routes.rb
Rails.application.routes.draw do
  resources :calculators
  
  get 'calculators/decking'
  devise_for :users
  get 'forms/show'
  get 'forms/new'
  get 'forms/create'
  get 'designs/index'
  get 'patios/index'
  get 'patios/sandstone'
  get 'patios/limestone'
  get 'patios/granite'
  get 'deckings/index'
  get 'deckings/budget'
  get 'deckings/softwood'
  get 'deckings/hardwood'
  get 'pages/about'
  get 'pages/calculator'
  root to: 'pages#home'
  resources :forms, only: [:show, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculator.rb
class Calculator < ApplicationRecord
end

app/models/form.rb
class Form < ApplicationRecord
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!
    before_action :set_copyright

    def set_copyright
        @copyright = PMaryonViewTool::Renderer.copyright('DeckDesign', 'All rights reserved')
    end
end
module PMaryonViewTool
    class Renderer
        def self.copyright (name, msg)
            "&copy; #{Time.now.year} | <p>#{name}</p> #{msg}".html_safe
        end
    end
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  def new
    @calculator = Calculator.new
  end

  def create
    @calculator = Calculator.new(calculator_params)
    if @calculator.save
      redirect_to root_path
    else
      render :new
    end
  end

  def decking
    @calculator = Calculator.all
  end
  private
  def calculator_params
    params.require(:calculator).permit(:name, :length, :width, :height, :price)
  end
end

app/controllers/deckings_controller.rb
class DeckingsController < ApplicationController
  def index
  end

  def budget
  end

  def softwood
  end

  def hardwood
  end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  def index
  end
end

app/controllers/enquires_controller.rb
class EnquiresController < ApplicationController
  def new
    @form = Form.new
  end

  def create

  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def show
  end

  def new
    @form = Form.new
  end

  def create
    @form = Form.new(form_params)
    if @form.save
      redirect_to root_path
    else  
      render :new
    end
  end

  private

  def form_params
    params.require(:form).permit(:first_name, :last_name, :address, :mobile, :email, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about
  end

  def calculator
  end
end

app/controllers/patios_controller.rb
class PatiosController < ApplicationController
  def index
    
  end
  
  def sandstone
  end

  def limestone
  end

  def granite
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculators/create.html.erb
<h1>Calculators#create</h1>
<p>Find me in app/views/calculators/create.html.erb</p>


        <%
=begin%>
 
            <p>Decking type</p>
            <div class=' material-list hidden'>
               
                <div ><p class=" btn btn-item">
                    <%= f.label :name %>:
                    <%= f.text_field :name %><br /></p>
                </div> 
     
                <p class=" btn btn-item pine">pine decking</p>
                <p class=" btn btn-item larch">larch decking</p>
                <p class=" btn btn-item balau">balau deckin</p>
            </div> 
        
<%
=end%>

app/views/calculators/decking.html.erb
<h2><%= @calculator_item.first.name %></h2>

<%= @calculator_item.each  do |item| %>
<p><%= item.name %></p>
<% end %>

app/views/calculators/new.html.erb
<div class="row calculator-outline">
    <h1 class="col-sm-12 text-center calculator-header">Material calculator</h1>
    <%= form_for @calculator do |f| %>
    <div class="material-items row col-sm-12">


        <div class="btn material-parameters material-name">
            <select name="deckings" id="material-list" >
                <option value="">--decking type--</option>
                <option value="pine-decking">Pine Decking</option>
                <option value="larch-decking">Larch Decking</option>
                <option value="balau-decking">Balau Decking</option>
            </select>
        </div> 
        <div class="material-parameters length dimensions">
            <p class= "mat-lenght" >
                <%= f.number_field :length, placeholder: 'length', class: "box-properties m-length" %><br />
            </p>
        </div>
        <div class="material-parameters dimensions">
            <p class= "mat-width">
                <%= f.number_field :width, placeholder: 'width', class: "box-properties m-width" %><br />
            </p>
        </div>
        <div class="material-parameters dimensions">
            <p class= "mat-height">
                <%= f.number_field :height, placeholder: 'height',class: "box-properties m-height" %><br />
            </p>
        </div>
        <div class="material-parameters dimensions">
            <p class="total-cost">£</p>
        </div>
        <div class="material-parameters dimensions">
            <button class="btn sum-up-btn">Calculate</button>
        </div>
  
    </div>
    <div class="material-items row col-sm-12">


        <div class="btn material-parameters material-name">
            <select name="sandstone-patios" id="material-list-patio" >
                <option value="">--patio type--</option>
                <option value="sawn-raj-green">Sawn Raj Green</option>
                <option value="riven-mint">Riven Mint</option>
                <option value="sawn-kandela-grey">Kandela Grey</option>
            </select>
        </div> 
        <div class="material-parameters length dimensions">
            <p class= "mat-lenght" >
                <%= f.number_field :length, placeholder: 'length', class: "box-properties p-length" %><br />
            </p>
        </div>
        <div class="material-parameters dimensions">
            <p class= "mat-width">
                <%= f.number_field :width, placeholder: 'width', class: "box-properties p-width" %><br />
            </p>
        </div>
        <div class="material-parameters dimensions">
           
            <select name="pattern" id="material-list" class="p-size">
            <option value="">--size--</option>
            <option value="300/300">300x300</option>
            <option value="300/450">300x450</option>
            <option value="300/600">300x600</option>
            <option value="600/600">600x600</option>
            <option value="600/900">600x900</option>
            <option value="4-random">4 random sizes</option>
            </select>
        </div>
        <div class="material-parameters dimensions">
            <p class="total-cost patio-cost">£</p>
        </div>
        <div class="material-parameters dimensions">
            <button class="btn sum-up-btn patio-btn">Calculate</button>
        </div>
  
    </div>
    <div class="material-items row col-sm-12">


        <div class="btn material-parameters material-name">
            <select name="turfs" id="material-list" class="t-type">
                <option value="">--turf type--</option>
                <option value="essex-turf">Essex Turf</option>
                <option value="medalion-turf">Medalion Turf</option>
                <option value="tough-sport-turf">Tough Sport Turf</option>
            </select>
        </div> 
        <div class="material-parameters length dimensions">
            <p class= "mat-lenght" >
                <%= f.number_field :length, placeholder: 'length', class: "box-properties t-length" %><br />
            </p>
        </div>
        <div class="material-parameters dimensions">
            <p class= "mat-width">
                <%= f.number_field :width, placeholder: 'width', class: "box-properties t-width" %><br />
            </p>
        </div>
        <div class="material-parameters dimensions">
            <p class= "mat-height">
                N/A
            </p>
        </div>
        <div class="material-parameters dimensions">
            <p class="total-cost turf-cost">£</p>
        </div>
        <div class="material-parameters dimensions">
            <button class="btn sum-up-btn t-btn">Calculate</button>
        </div>
  
    </div>
    <div class="material-items row col-sm-12">


        <div class="btn material-parameters material-name">
            <select name="fencess" id="material-list" >
                <option value="">--fence type--</option>
                <option value="panel-fence">Panel Fence</option>
                <option value="horizontal-slatted-fence">Horizontal Slatted Fence</option>
                <option value="Vertical-slatted-fence">Vertical Slatted Fence</option>
            </select>
        </div> 
        <div class="material-parameters length dimensions">
            <p class= "mat-lenght" >
                <%= f.number_field :length, placeholder: 'length', class: "box-properties fence-length" %><br />
            </p>
        </div>
        <div class="material-parameters dimensions">
            
            <select name="planks" id="material-list">
            <option value="">--size--</option>
            <option value="19x38-plank">19x38</option>
            <option value="25x50">25x50</option>
            <option value="19x70">19x70</option>
            <option value="19x90">19x90</option>
            </select>
        </div>
        <div class="material-parameters dimensions">
            <p class= "mat-height">
                <%= f.number_field :height, placeholder: 'height',class: "box-properties fence-height" %><br />
            </p>
        </div>
        <div class="material-parameters dimensions">
            <p class="total-cost fence-cost">£</p>
        </div>
        <div class="material-parameters dimensions">
            <button class="btn sum-up-btn fence-button">Calculate</button>
        </div>
  
    </div>
    <div class="material-items row col-sm-12 summary-items">
        <div class="summary estimated-cost">
            <p>Estimeted cost</p>
        </div>
        <div class="summary total-figure">
            <p>£0</p>
        </div>
        <div class="summary book-now-button">
            <%= f.submit "Book Now", class:"form-submit-btn"%>
        </div>
    </div>
    <h2 class="col-sm-12 text-center calculator-footer">Additional transport costs may apply</h2>
    <% end %>
</div>

app/views/deckings/_decking_page.html.erb
<%= link_to deckings_index_path, class:"page-links" do %>
<div class="page-links">
  <h2>BACK</h2>
</div>
<% end %>

app/views/deckings/budget.html.erb
  <h1 class="page-header">Budget decking</h1>
  <%= render "decking_page" %>
  <div id="carouselExampleIndicators" class="carousel slide col-12" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
      <%= cl_image_tag("Deck%20Design/Decking/budget/budget-decking-treated-pine%20wood.jpg", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
      <%= cl_image_tag("Deck%20Design/Decking/budget/Budget-decking-pine-platform.jpg", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Decking/budget/budget-decking-pine.jpg", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="decking-description">
    <h1 class="product-header-h1">Budget Decking</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maxime est quae assumenda expedita voluptatibus ratione alias consectetur officiis deserunt laudantium temporibus natus, veritatis laboriosam aut debitis suscipit omnis nisi optio pariatur tempore doloremque. Nostrum praesentium repudiandae aliquid, nesciunt assumenda facilis aperiam sunt atque officiis eum tenetur tempore quae ipsam.</p>
  </div>
  <div class="gray"></div>

app/views/deckings/hardwood.html.erb
  <h1 class="page-header">Hardwood Decking</h1>
  <%= render "decking_page" %>


  <div id="carouselExampleIndicators" class="carousel slide col-12" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
      <%= cl_image_tag("Deck%20Design/Decking/hardwood/large-hardwood-decking.jpg", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
      <%= cl_image_tag("Deck%20Design/Decking/hardwood/veranda-decking-hardwood-decking.jpg", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Decking/hardwood/yellow-balau-hardwood-decking-2", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Decking/hardwood/yellow-balau-hardwood-decking-steps", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Decking/hardwood/yellow-balau-hardwood-decking-garden", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Decking/hardwood/yellow-balau-hardwood-decking", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Decking/hardwood/contemporary-hardwood-decking", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Decking/hardwood/hardwood-decking-garden", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Decking/hardwood/hardwood-decking-modern", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Decking/hardwood/hardwood-decking", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
    <div class="decking-description">
    <h1 class="product-header-h1">Hardwood Decking</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maxime est quae assumenda expedita voluptatibus ratione alias consectetur officiis deserunt laudantium temporibus natus, veritatis laboriosam aut debitis suscipit omnis nisi optio pariatur tempore doloremque. Nostrum praesentium repudiandae aliquid, nesciunt assumenda facilis aperiam sunt atque officiis eum tenetur tempore quae ipsam.</p>
  </div>
  <div class="gray"></div>

app/views/deckings/index.html.erb
<div class="container-home">
  <div class="material-list">
    <div class="row">
      <div class="material-types-decking col-8 ">
        <%= link_to deckings_budget_path, class:"material-button" do %>
          <h2 class="material-names">Budget Decking</h2>
        <% end %>
      </div>
      <div class="material-types-decking col-7 ">
        <%= link_to deckings_softwood_path, class:"material-button" do %>
          <h2 class="material-names">Softwood Decking</h2>
        <% end %>
      </div>
      <div class="material-types-decking col-8 ">
        <%= link_to deckings_hardwood_path, class:"material-button" do %>
          <h2 class="material-names">Hardwood Decking</h2>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/designs/index.html.erb
<h1 class="page-header">3D design</h1>
  <div id="carouselExampleIndicators" class="carousel slide col-12" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
      <%= cl_image_tag("Deck%20Design/Design/garden-design-mill-hill.jpg", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
      <%= cl_image_tag("Deck%20Design/Patio/limestone/limestone-circle.jpg", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag("Deck%20Design/Patio/limestone/limestone-patio.jpg", :transformation=>[
    {:height=>600, :width=>1200, :crop=>"fill"},
    {:gravity=>"center", :height=>400, :overlay=>"logo:deckDesign-logo.png", :opacity=>25, :width=>400, :crop=>"fill"}
    ]) %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="decking-description">
    <h2 class="product-header-h1">3D Design Services </h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque maxime est quae assumenda expedita voluptatibus ratione alias consectetur officiis deserunt laudantium temporibus natus, veritatis laboriosam aut debitis suscipit omnis nisi optio pariatur tempore doloremque. Nostrum praesentium repudiandae aliquid, nesciunt assumenda facilis aperiam sunt atque officiis eum tenetur tempore quae ipsam.</p>
  </div>
  <div class="gray"></div>

app/views/enquires/create.html.erb
<h1>Enquires#create</h1>
<p>Find me in app/views/enquires/create.html.erb</p>

app/views/enquires/new.html.erb
<%= render "pages/form" %>

app/views/forms/_contact.html.erb
<div class="sticky-modal">
  <button type="button" class="btn btn-secondary btn-lg" data-toggle="modal" data-target="#exampleModal">
    Contact
  </button>
</div>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="contact">
            <h2>mobile</h2>
            <p>077 7777 7777</p>
            <h2>email</h2>
            <p>contact@deck-design.co.uk</p>
          </div>>
        </div>
      </div>
    </div>
  </div>

app/views/forms/create.html.erb
<h1>Forms#create</h1>
<p>Find me in app/views/forms/create.html.erb</p>

app/views/pages/_form.html.erb
<%= simple_form_for  @form do |f|%>
<%= f.label :name %>
<%= f.text_fiels :name %>
<%= f.label :surname %>
<%= f.text_field :surname %>
<%= f.label :mobile %>
<%= f.integer :mobile %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :budget %>
<%= f.integer :budget %>
<%= f.submit %>
<% end %>

app/views/pages/_navbar.html.erb
 <div class="navbar-list ">
  <div class="col-5 navbar-boxes" >
    <div class="material-types">
      <%= link_to designs_index_path, class:"material-button" do %>     
          <h2 class="navbar-names">Design</h2>       
      <% end %>
    </div>
    <div class="material-types">
      <%= link_to deckings_index_path, class:"material-button" do %>    
          <h2 class="navbar-names">Decking</h2>   
      <% end %>
    </div>
  </div>
  <div class="col-2 navbar-boxes" >
    <div class="image">
      <%= link_to root_path, class:"links" do  %>
        <%= image_tag ("logos/deckDesign-2.png"), class: "logo-image" %>
      <% end %>
    </div>
  </div>
  <div class="col-5 navbar-boxes" >
    <div class="material-types">
      <%= link_to patios_index_path, class:"material-button" do %>  
          <h2 class="navbar-names">Patio</h2>        
      <% end %>
    </div>
    <div class="material-types">
      <%= link_to pages_about_path, class:"material-button" do %>  
          <h2 class="navbar-names">About</h2>        
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-home row">
    <div class="homepage-header text-center">
        <h1>Create your garden a perfect outdoor living space with Deck Design</h1>

        <div class="search-homepage">
            <div class="row search-input">
                <div class="col-7 input-field-padding res-768px">
                    <input class="input-field" type="text" placeholder="what would you like to build?">
                </div>
                <div class="col-5 btn btn-secondary btn-lg"><%= link_to "Get Instant Quote!", new_calculator_path  %></div>
            </div>
            <div class="btn btn-dark btn-block quotes-padding"><%= link_to "Contact Us", forms_new_path  %></div>
        </div>

    </div>
</div>
<div class="container home-page-bottom">
    <h2>Our Decking Selection</h2>
    <div class="row ">
        <div class="col-sm">
            <%= link_to deckings_hardwood_path, class:"card-link" do %>
                <div class=" card" style="width: 18rem;">
                    <%= cl_image_tag("Deck%20Design/Decking/hardwood/large-hardwood-decking.jpg", :class => "card-img-top")%>
                    <div class="card-body bottom-card">
                        <h2>Hardwood decking</h2>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="col-sm">
            <%= link_to deckings_softwood_path, class:"card-link" do %>
                <div class="card" style="width: 18rem;">
                    <%= cl_image_tag("Deck%20Design/Decking/softwood/contemporary-cedar-decking", :class => "card-img-top") %>
                    <div class="card-body bottom-card">
                        <h2>Softwood decking</h2>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="col-sm">
            <%= link_to deckings_budget_path, class:"card-link" do %>
                <div class="card " style="width: 18rem;">
                    <%= cl_image_tag("Deck%20Design/Decking/budget/budget-decking-treated-pine%20wood.jpg", :class => "card-img-top") %>
                    <div class="card-body bottom-card">
                        <h2>Budget decking</h2>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/patios/_patio_page.html.erb
<%= link_to patios_index_path, class:"page-links" do %>
  <h2>BACK</h2>
<% end %>

app/views/patios/index.html.erb
<div class="container-home">
  <div class="material-list">
    <div class="row">
      <div class="material-types-decking col-xl-8 col-sm-12">
        <%= link_to patios_sandstone_path, class:"material-button" do %>
          <h2 class="material-names">Sandstone</h2>
        <% end %>
      </div>
      <div class="material-types-decking col-xl-7 col-sm-12">
        <%= link_to patios_limestone_path, class:"material-button" do %>
          <h2 class="material-names">Limestone</h2>
        <% end %>
      </div>
      <div class="material-types-decking col-xl-8 col-sm-12 ">
        <%= link_to patios_granite_path, class:"material-button" do %>
          <h2 class="material-names">Granite</h2>        
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="inner">
    <%= @copyright %>
</div>